baseURL = "https://zmoog.dev/"
languageCode = "en-us"
title = "zmoog"
theme = "lanyon-hugo"
googleAnalytics = "UA-189846455-1"

[Params]
  title = "zmoog"
  tagline = "I procrastinate things"
  author = "Maurizio Branca"